spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=PadelDB;encrypt=false;trustServerCertificate=true
    username: sa
    password: PadelDB!2026
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver



server:
  port: 8080

jwt:
  secret: PadelProjetJWTSecretKeyMinimum32CharactersLong!!!
  expiration: 3600000
  refresh-expiration: 86400000